# Generated by Django 4.1.1 on 2022-12-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employee_data',
        ),
    ]
